server:
  port: 8082

spring:
  application:
    name: service-log
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9200

#  elasticsearch:
#    host: localhost
#    port: 9200
#    username: elastic
#    password: changeme
#    connection-timeout: 1000
#    socket-timeout: 3000

logging:
  level:
    root: INFO
